# Generated by Django 5.2 on 2025-04-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tg_usename',
            new_name='tg_username',
        ),
    ]
