# Generated by Django 5.2 on 2025-04-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
